post_install() {
  tput setaf 2;echo "Enabling teamviewerd.service";tput sgr0
  systemctl enable teamviewerd.service
  tput setaf 2;echo "Starting teamviewerd.service";tput sgr0
  systemctl start teamviewerd.service
}

post_upgrade() {
  post_install
}

post_remove() {
  systemctl stop teamviewerd.service
  systemctl disable teamviewerd.service
  #systemctl daemon-reload
  rm -rf /opt/teamviewer
}

# vim: ts=2 sw=2 et:
