post_install() {
if systemctl --all --type service | grep -q "virtual-machine-check";then
    systemctl disable virtual-machine-check.service
fi
}

post_upgrade() {
if systemctl --all --type service | grep -q "virtual-machine-check";then
    systemctl disable virtual-machine-check.service
fi
}

pre_remove() {
if systemctl --all --type service | grep -q "virtual-machine-check";then
    systemctl disable virtual-machine-check.service
fi
}
