post_upgrade() {
	if usr/bin/pacman-key -l >/dev/null 2>&1; then
		usr/bin/pacman-key --populate arcolinux
		#marco
		pacman-key --lsign-key F1ABB772CE9F7FC0
	else
		echo " >>> Run \`pacman-key --init\` to set up your pacman keyring."
		echo " >>> Then run \`pacman-key --populate arcolinux\` to install the ArcoLinux keyring."
	fi
}

post_install() {
	if [ -x usr/bin/pacman-key ]; then
		post_upgrade
	fi
}
