#!/bin/bash
#set -e
##################################################################################################################
# Author 	: Erik Dubois
# Website : https://www.erikdubois.be
# Website	:	https://www.arcolinux.info
# Website	:	https://www.arcolinux.com
# Website	:	https://www.arcolinuxd.com
# Website : https://www.arcolinuxb.com
# Website : https://www.arcolinuxiso.com
# Website	:	https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################

desktop=$DESKTOP_SESSION
case $desktop in
    herbstluftwm|/usr/share/xsessions/herbstluftwm )
      herbstclient quit
      ;;
    bspwm|/usr/share/xsessions/bspwm )
      pkill bspwm
      ;;
    jwm|/usr/share/xsessions/jwm )
      pkill jwm
      ;;
    openbox|/usr/share/xsessions/openbox )
      pkill openbox
      ;;
    awesome|/usr/share/xsessions/awesome )
      pkill awesome
      ;;
    qtile|/usr/share/xsessions/qtile )
      pkill qtile
	  #qtile-cmd -o cmd -f shutdown
      ;;
    xmonad|/usr/share/xsessions/xmonad )
      pkill xmonad
      ;;
    dwm|/usr/share/xsessions/dwm )
      pkill dwm
      ;;
    * )
      echo "#################################"
      echo "error"
      echo "#################################"
      ;;
esac
