post_install() {
    echo -e "\n** The files have been installed in /etc/skel/.config/icewm **\n"
    if pacman -Qi icewm &> /dev/null; then
    cp /usr/share/xsessions/icewm.desktop.arcolinux /usr/share/xsessions/icewm.desktop
    fi
}

post_upgrade() {
    post_install
}

pre_remove() {

  if pacman -Qi icewm &> /dev/null; then
		cp /usr/share/xsessions/icewm.desktop.orginal /usr/share/xsessions/icewm.desktop
  fi

}
